### ISSUE TITLE
Fails to build on Manjaro X64

### ISSUE THREAD

**Issue by coreybruce** [rosskidson/nestris_x86#1]
Hey there I just wanted to report that it fails to build on Manjaro X64, I have sdl and sdl mixer installed but it this is the log

```
[ 51%] Building CXX object CMakeFiles/nestris_x86.dir/src/drawing_utils.cpp.o
In file included from /home/corey/Stuff/Projects/nestris_x86/include/drawing_utils.hpp:3,
                 from /home/corey/Stuff/Projects/nestris_x86/src/drawing_utils.cpp:1:
/home/corey/Stuff/Projects/nestris_x86/include/drawers/pixel_drawing_interface.hpp:21:5: error: ‘uint8_t’ does not name a type
   21 |     uint8_t r;
      |     ^~~~~~~
/home/corey/Stuff/Projects/nestris_x86/include/drawers/pixel_drawing_interface.hpp:5:1: note: ‘uint8_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
    4 | #include <string>
  +++ |+#include <cstdint>
    5 | 
/home/corey/Stuff/Projects/nestris_x86/include/drawers/pixel_drawing_interface.hpp:22:5: error: ‘uint8_t’ does not name a type
   22 |     uint8_t g;
      |     ^~~~~~~
/home/corey/Stuff/Projects/nestris_x86/include/drawers/pixel_drawing_interface.hpp:22:5: note: ‘uint8_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
/home/corey/Stuff/Projects/nestris_x86/include/drawers/pixel_drawing_interface.hpp:23:5: error: ‘uint8_t’ does not name a type
   23 |     uint8_t b;
      |     ^~~~~~~
/home/corey/Stuff/Projects/nestris_x86/include/drawers/pixel_drawing_interface.hpp:23:5: note: ‘uint8_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
/home/corey/Stuff/Projects/nestris_x86/include/drawers/pixel_drawing_interface.hpp:24:5: error: ‘uint8_t’ does not name a type
   24 |     uint8_t a;
      |     ^~~~~~~
/home/corey/Stuff/Projects/nestris_x86/include/drawers/pixel_drawing_interface.hpp:24:5: note: ‘uint8_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
/home/corey/Stuff/Projects/nestris_x86/include/drawers/pixel_drawing_interface.hpp: In static member function ‘static nestris_x86::PixelDrawingInterface::Color nestris_x86::PixelDrawingInterface::WHITE()’:
/home/corey/Stuff/Projects/nestris_x86/include/drawers/pixel_drawing_interface.hpp:26:57: error: too many initializers for ‘nestris_x86::PixelDrawingInterface::Color’
   26 |   static Color WHITE() { return Color{255, 255, 255, 255}; }
      |                                                         ^
/home/corey/Stuff/Projects/nestris_x86/include/drawers/pixel_drawing_interface.hpp: In static member function ‘static nestris_x86::PixelDrawingInterface::Color nestris_x86::PixelDrawingInterface::BLACK()’:
/home/corey/Stuff/Projects/nestris_x86/include/drawers/pixel_drawing_interface.hpp:27:51: error: too many initializers for ‘nestris_x86::PixelDrawingInterface::Color’
   27 |   static Color BLACK() { return Color{0, 0, 0, 255}; }
      |                                                   ^
/home/corey/Stuff/Projects/nestris_x86/include/drawers/pixel_drawing_interface.hpp: In static member function ‘static nestris_x86::PixelDrawingInterface::Color nestris_x86::PixelDrawingInterface::GREY()’:
/home/corey/Stuff/Projects/nestris_x86/include/drawers/pixel_drawing_interface.hpp:28:56: error: too many initializers for ‘nestris_x86::PixelDrawingInterface::Color’
   28 |   static Color GREY() { return Color{192, 192, 192, 255}; }
      |                                                        ^
/home/corey/Stuff/Projects/nestris_x86/include/drawers/pixel_drawing_interface.hpp: In static member function ‘static nestris_x86::PixelDrawingInterface::Color nestris_x86::PixelDrawingInterface::DARK_GREY()’:
/home/corey/Stuff/Projects/nestris_x86/include/drawers/pixel_drawing_interface.hpp:29:61: error: too many initializers for ‘nestris_x86::PixelDrawingInterface::Color’
   29 |   static Color DARK_GREY() { return Color{128, 128, 128, 255}; }
      |                                                             ^
/home/corey/Stuff/Projects/nestris_x86/include/drawers/pixel_drawing_interface.hpp: In static member function ‘static nestris_x86::PixelDrawingInterface::Color nestris_x86::PixelDrawingInterface::RED()’:
/home/corey/Stuff/Projects/nestris_x86/include/drawers/pixel_drawing_interface.hpp:30:51: error: too many initializers for ‘nestris_x86::PixelDrawingInterface::Color’
   30 |   static Color RED() { return Color{255, 0, 0, 255}; }
      |                                                   ^
/home/corey/Stuff/Projects/nestris_x86/include/drawers/pixel_drawing_interface.hpp: In static member function ‘static nestris_x86::PixelDrawingInterface::Color nestris_x86::PixelDrawingInterface::GREEN()’:
/home/corey/Stuff/Projects/nestris_x86/include/drawers/pixel_drawing_interface.hpp:31:53: error: too many initializers for ‘nestris_x86::PixelDrawingInterface::Color’
   31 |   static Color GREEN() { return Color{0, 255, 0, 255}; }
      |                                                     ^
/home/corey/Stuff/Projects/nestris_x86/include/drawers/pixel_drawing_interface.hpp: In static member function ‘static nestris_x86::PixelDrawingInterface::Color nestris_x86::PixelDrawingInterface::BLUE()’:
/home/corey/Stuff/Projects/nestris_x86/include/drawers/pixel_drawing_interface.hpp:32:52: error: too many initializers for ‘nestris_x86::PixelDrawingInterface::Color’
   32 |   static Color BLUE() { return Color{0, 0, 255, 255}; }
      |                                                    ^
/home/corey/Stuff/Projects/nestris_x86/include/drawers/pixel_drawing_interface.hpp: In static member function ‘static nestris_x86::PixelDrawingInterface::Color nestris_x86::PixelDrawingInterface::YELLOW()’:
/home/corey/Stuff/Projects/nestris_x86/include/drawers/pixel_drawing_interface.hpp:33:56: error: too many initializers for ‘nestris_x86::PixelDrawingInterface::Color’
   33 |   static Color YELLOW() { return Color{255, 255, 0, 255}; }
      |                                                        ^
[ 54%] Building CXX object CMakeFiles/nestris_x86.dir/src/drawers/olc_drawer.cpp.o
[ 57%] Building CXX object CMakeFiles/nestris_x86.dir/src/frame_processors/game_processor.cpp.o
make[2]: *** [CMakeFiles/nestris_x86.dir/build.make:146: CMakeFiles/nestris_x86.dir/src/drawing_utils.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 60%] Linking CXX executable asset_cpp_gen
[ 60%] Built target asset_cpp_gen
make[1]: *** [CMakeFiles/Makefile2:144: CMakeFiles/nestris_x86.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```

**Comment by rosskidson** [comment]
The first error looks like a missing include, can you try adding 
```
#include <cstdint>
```

To the includes of  `nestris_x86/include/drawers/pixel_drawing_interface.hpp` ?

**Comment by coreybruce** [comment]
> #include <cstdint>

Wow quick reply!

Yep that solved the issue and it builds, thanks so much! should I close the issue or is there anything else you what to test/check?

**Comment by rosskidson** [comment]
Let's leave it open until I commit the fix.

Just FYI: There is a branch that is a little bit ahead of master (linux-devel).  The changes are mostly about controller compatibility and configuration.  I haven't merged it because I didn't test it on Windows, but moving forward I think I will drop official windows support and just merge it.  In the meantime you can try this branch if you like.

**Comment by coreybruce** [comment]
ok sweet

Ahh right I see and oh really? is it not working on Windows or something?

By the way I know it's off topic to this issue but firstly I want to say this is a awesome project and my first question is when will the music be supported? the game runs great and all that but it isn't quite the same without the iconic music, I would really love to see the music eventually supported.

My second question is would there be support for setting it to fullscreen different Windows sizes with with a option menu or a config file?

3rd I think the project name  nestris_x86  doesn't seem to fit anymore since you can compile and run it on different architectures like Arm or Arm64, I have actually compiled this on Manjaro Arm64 and didn't run into this build issue but the game runs great  so I think it would be better to sorten the name to just Nestris but that's just my opinion.

**Comment by rosskidson** [comment]
Thanks for the feedback!

**Comment by rosskidson** [comment]
Thanks for the feedback!

There's no problem with Windows, I'm afraid I just don't have the time/energy/experience/proper Windows development setup to test all the changes in Windows.  I develop in Linux, porting to Mac was very easy, Windows was a whole extra effort (at least for me). If someone else can help in this matter that would be welcome.

1. At this stage of the project I don't intend to implement everything, its more or less feature by request, so yeah adding music is something I could look into. I could even add the classic gameboy music as well in that case.
2. So the window is re sizable, do you mean that the resize persists after restarting the program, or do you want a proper fullscreen option without the window bar at the top? Or both?  I think this should all be possible
3. Very good point. The term Nestris is a little overloaded so I wanted to add something to make it unique, but indeed x64 is not suitable.  I will take this into consideration.

**Comment by coreybruce** [comment]
Ah ok that's understandable, while a bunch of my apps are multiplatform I mainly focus on Linux development myself but I could test the Windows version if you want as I also have a Windows 11 dual boot I barely use.

Awesome it would really complete the feeling of the game if it had the music! oh okay I gotcha so it's got most of the stuff but your just focusing on feature requests if there is any :smile: 

Yeah like have a persistent window size or have options for windows sizes you can set and a fullscreen option if possible

**Comment by coreybruce** [comment]
Oh and a bug I noticed that could be causing some minor frame frame dropping on Manjaro Arm64 the raspberry pi 4 which I noticed on the fps counter on the top is when the game is running I get a bunch of extra stuff in the log and will continue for ever with random numbers

```
[corey@corey-pi4 build]$ ./nestris
[INFO] assets.cpp:81: Loading sprites...
[INFO] assets.cpp:110: Loading sounds...
[INFO] nestris_x86.cpp:189: Frame reset to : 1704797472604457
[INFO] nestris_x86.cpp:189: Frame reset to : 1704797472722292
[INFO] nestris_x86.cpp:189: Frame reset to : 1704797472787797
[INFO] nestris_x86.cpp:189: Frame reset to : 1704797472851787
[INFO] nestris_x86.cpp:189: Frame reset to : 1704797472891765
[INFO] nestris_x86.cpp:189: Frame reset to : 1704797472960724
[INFO] nestris_x86.cpp:189: Frame reset to : 1704797472996600
[INFO] nestris_x86.cpp:189: Frame reset to : 1704797473031703
[INFO] nestris_x86.cpp:189: Frame reset to : 1704797473066376
[INFO] nestris_x86.cpp:189: Frame reset to : 1704797473124705
[INFO] nestris_x86.cpp:189: Frame reset to : 1704797473187080
[INFO] nestris_x86.cpp:189: Frame reset to : 1704797473226668
[INFO] nestris_x86.cpp:189: Frame reset to : 1704797473306688
[INFO] nestris_x86.cpp:189: Frame reset to : 1704797473341947
[INFO] nestris_x86.cpp:189: Frame reset to : 1704797473376770
```

Not sure if this is a bug or not but it doesn't do this when it's running on Manjaro x64

**Comment by rosskidson** [comment]
> Ah ok that's understandable, while a bunch of my apps are multiplatform I mainly focus on Linux development myself but I could test the Windows version if you want as I also have a Windows 11 dual boot I barely use.

Honestly if you could just check that it still builds and runs normally then that would already be a huge help!

Really nice you got it running on a pi.  I will now break up all these requests / bug report into separate issues and comment on each of them as I work on them one by one.

**Comment by coreybruce** [comment]
> > Ah ok that's understandable, while a bunch of my apps are multiplatform I mainly focus on Linux development myself but I could test the Windows version if you want as I also have a Windows 11 dual boot I barely use.
> 
> Honestly if you could just check that it still builds and runs normally then that would already be a huge help!
> 
> Really nice you got it running on a pi. I will now break up all these requests / bug report into separate issues and comment on each of them as I work on them one by one.

I haven't got much experience with building stuff on Windows but I can give it a go even tho I have experience with how bad/retarded Windows CMD commands and powershell is but I will also defiantly test the Windows Binary you've  already compiled to make sure it works.

Yep, works with the same build instructions for Linux no problems at all other then that issue I did mention when it runs.

I'll move that to the new report you made also. :+1:

**Comment by coreybruce** [comment]
Oh since you have been so nice @rosskidson I wanted to let you know that I have a bunch of projects on my Gitlab repo where I compile and host the binary files for different architectures and repackage them with a nice graphical setup script for my AUR packages and was thinking of repackaging this awesome project as a Tetris package powered by nestris, is that all good?

**Comment by rosskidson** [comment]
hmm I don't know anything about AUR packages or Arch linux, but sure, I don't see why not.  Could you provide a few links so I can see where this package would be published?

**Comment by rosskidson** [comment]
One thing you should keep in mind is that the name Tetris is a trademark owned by the Tetris Company.  That company are known for chasing down tetris clones, anything that bares the name Tetris or has similar gameplay.  I wouldn't be surprised if this project itself could be an issue, but at least at the moment I assume its too niche/unknown for them to care.  Nevertheless I would at least be careful with using the 'Tetris' name.

https://en.wikipedia.org/wiki/The_Tetris_Company

**Comment by coreybruce** [comment]
Yeah right I see, I'll see what happens there tho are a few tetris projects mainly clones now but I was thinking of calling it tetris-nes. I already have a Gitlab repo setup with the 0.7 binaries for x64 and arm64 currently and still got more to update and add to the repo. https://gitlab.com/tetris-nes

What are your thoughts?

With updates to this project is it going to take advantage of something like a config file for settings like Window size, fullscreen mode and other set settings that would be set in the options in the future?

**Comment by coreybruce** [comment]
I just tested the Windows binary on Windows 11 and I can confirm it works without any issues, I did see one line say ```nestris_x86.cpp:189: Frame reset to``` but it didn't keep going like it does on Arm Linux . I honestly couldn't be bothered to setup all the development stuff on Windows to attempt to build it but it should be fine to continue just for the sake of supporting all the platforms.

**Comment by rosskidson** [comment]
> Yeah right I see, I'll see what happens there tho are a few tetris projects mainly clones now but I was thinking of calling it tetris-nes. I already have a Gitlab repo setup with the 0.7 binaries for x64 and arm64 currently and still got more to update and add to the repo. https://gitlab.com/tetris-nes
> 
> What are your thoughts?

Fine for me

> 
> With updates to this project is it going to take advantage of something like a config file for settings like Window size, fullscreen mode and other set settings that would be set in the options in the future?

The latest version on master now uses a `config.yaml` that resides next to the binary.  It currently contains all the current settings and keybindings. I will use this for the window size settings as well.

**Comment by coreybruce** [comment]
Awesome and Oh right nice. I have pulled the latest commit and recompiled it but I didn't see a config.yaml get created in the same location as the binary, is it supposed to create the file on launch? 

Will this count as a new version 0.8 by the way?

**Comment by rosskidson** [comment]
It saves the `config.yaml` when you start a game.

I will address some of the other issues before, and make a few other minor changes before the next release.

**Comment by coreybruce** [comment]
Ah I see, the reason I asked is because I haven't need a config.yaml  file get created when I launch the game.

Ok no problem :+1:
